<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Anubis.Application\Anubis.Application.csproj" />
    <ProjectReference Include="..\Anubis.Infrastructure\Anubis.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <StackTraceSupport>true</StackTraceSupport>
  </PropertyGroup>

</Project>
